### ISSUE TITLE
WP GraphQL included by default. Requirement or leftover?

### ISSUE THREAD

**Issue by a-barbieri** [valu-digital/wp-testing-tools#4]
I guess you haven't removed WP GraphQL by mistake. Or not?

https://github.com/valu-digital/wp-testing-tools/blob/18e0bd2670901afcde906e897f121bead1c66eb5/plugin/composer.wp-install.json#L13

**Comment by a-barbieri** [comment]
Sorry, I've read the guideline more carefully and it's actually something done on purpose.

**Comment by esamattis** [comment]
Ya, it's just as an example in there. Nothing wp-graphql specific in this.
